/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedMicrocyclesRouteImport } from './routes/_authenticated/microcycles'
import { Route as AuthenticatedPreseasonRouteImport } from './routes/_authenticated/preseason'
import { Route as AuthenticatedSeasonRouteImport } from './routes/_authenticated/season'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as EjerciciosFutbolBaseRouteImport } from './routes/ejercicios.futbol-base'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedExercisesIndexRouteImport } from './routes/_authenticated/exercises.index'
import { Route as AuthenticatedExercisesIdRouteImport } from './routes/_authenticated/exercises.$id'
import { Route as AuthenticatedMicrocyclesIndexRouteImport } from './routes/_authenticated/microcycles.index'
import { Route as AuthenticatedMicrocyclesIdRouteImport } from './routes/_authenticated/microcycles.$id'
import { Route as AuthenticatedMicrocyclesNewRouteImport } from './routes/_authenticated/microcycles.new'
import { Route as AuthenticatedPreseasonIndexRouteImport } from './routes/_authenticated/preseason.index'
import { Route as AuthenticatedPreseasonIdRouteImport } from './routes/_authenticated/preseason.$id'
import { Route as AuthenticatedSeasonIndexRouteImport } from './routes/_authenticated/season.index'
import { Route as AuthenticatedSeasonIdRouteImport } from './routes/_authenticated/season.$id'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions.index'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as AuthenticatedSessionsNewRouteImport } from './routes/_authenticated/sessions.new'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiRpcSecurityProbeRouteImport } from './routes/api/rpc/security-probe'
import { Route as EjerciciosFutbolBaseSlugRouteImport } from './routes/ejercicios.futbol-base.$slug'
import { Route as ApiPublicSecurityCspRouteImport } from './routes/api/public/security/csp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMicrocyclesRoute =
  AuthenticatedMicrocyclesRouteImport.update({
    id: '/microcycles',
    path: '/microcycles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreseasonRoute = AuthenticatedPreseasonRouteImport.update({
  id: '/preseason',
  path: '/preseason',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeasonRoute = AuthenticatedSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EjerciciosFutbolBaseRoute = EjerciciosFutbolBaseRouteImport.update({
  id: '/ejercicios/futbol-base',
  path: '/ejercicios/futbol-base',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedExercisesIndexRoute =
  AuthenticatedExercisesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)
const AuthenticatedExercisesIdRoute =
  AuthenticatedExercisesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)
const AuthenticatedMicrocyclesIndexRoute =
  AuthenticatedMicrocyclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMicrocyclesRoute,
  } as any)
const AuthenticatedMicrocyclesIdRoute =
  AuthenticatedMicrocyclesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMicrocyclesRoute,
  } as any)
const AuthenticatedMicrocyclesNewRoute =
  AuthenticatedMicrocyclesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMicrocyclesRoute,
  } as any)
const AuthenticatedPreseasonIndexRoute =
  AuthenticatedPreseasonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPreseasonRoute,
  } as any)
const AuthenticatedPreseasonIdRoute =
  AuthenticatedPreseasonIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPreseasonRoute,
  } as any)
const AuthenticatedSeasonIndexRoute =
  AuthenticatedSeasonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSeasonRoute,
  } as any)
const AuthenticatedSeasonIdRoute = AuthenticatedSeasonIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSeasonRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSessionsRoute,
} as any)
const AuthenticatedSessionsNewRoute =
  AuthenticatedSessionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSecurityProbeRoute = ApiRpcSecurityProbeRouteImport.update({
  id: '/api/rpc/security-probe',
  path: '/api/rpc/security-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const EjerciciosFutbolBaseSlugRoute =
  EjerciciosFutbolBaseSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => EjerciciosFutbolBaseRoute,
  } as any)
const ApiPublicSecurityCspRoute = ApiPublicSecurityCspRouteImport.update({
  id: '/api/public/security/csp',
  path: '/api/public/security/csp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/microcycles': typeof AuthenticatedMicrocyclesRouteWithChildren
  '/preseason': typeof AuthenticatedPreseasonRouteWithChildren
  '/season': typeof AuthenticatedSeasonRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/ejercicios/futbol-base': typeof EjerciciosFutbolBaseRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/microcycles/$id': typeof AuthenticatedMicrocyclesIdRoute
  '/microcycles/new': typeof AuthenticatedMicrocyclesNewRoute
  '/preseason/$id': typeof AuthenticatedPreseasonIdRoute
  '/season/$id': typeof AuthenticatedSeasonIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/rpc/security-probe': typeof ApiRpcSecurityProbeRoute
  '/ejercicios/futbol-base/$slug': typeof EjerciciosFutbolBaseSlugRoute
  '/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/microcycles/': typeof AuthenticatedMicrocyclesIndexRoute
  '/preseason/': typeof AuthenticatedPreseasonIndexRoute
  '/season/': typeof AuthenticatedSeasonIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/api/public/security/csp': typeof ApiPublicSecurityCspRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/team': typeof AuthenticatedTeamRoute
  '/ejercicios/futbol-base': typeof EjerciciosFutbolBaseRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/microcycles/$id': typeof AuthenticatedMicrocyclesIdRoute
  '/microcycles/new': typeof AuthenticatedMicrocyclesNewRoute
  '/preseason/$id': typeof AuthenticatedPreseasonIdRoute
  '/season/$id': typeof AuthenticatedSeasonIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/rpc/security-probe': typeof ApiRpcSecurityProbeRoute
  '/ejercicios/futbol-base/$slug': typeof EjerciciosFutbolBaseSlugRoute
  '/exercises': typeof AuthenticatedExercisesIndexRoute
  '/microcycles': typeof AuthenticatedMicrocyclesIndexRoute
  '/preseason': typeof AuthenticatedPreseasonIndexRoute
  '/season': typeof AuthenticatedSeasonIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/api/public/security/csp': typeof ApiPublicSecurityCspRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/_authenticated/microcycles': typeof AuthenticatedMicrocyclesRouteWithChildren
  '/_authenticated/preseason': typeof AuthenticatedPreseasonRouteWithChildren
  '/_authenticated/season': typeof AuthenticatedSeasonRouteWithChildren
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/ejercicios/futbol-base': typeof EjerciciosFutbolBaseRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/_authenticated/microcycles/$id': typeof AuthenticatedMicrocyclesIdRoute
  '/_authenticated/microcycles/new': typeof AuthenticatedMicrocyclesNewRoute
  '/_authenticated/preseason/$id': typeof AuthenticatedPreseasonIdRoute
  '/_authenticated/season/$id': typeof AuthenticatedSeasonIdRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/rpc/security-probe': typeof ApiRpcSecurityProbeRoute
  '/ejercicios/futbol-base/$slug': typeof EjerciciosFutbolBaseSlugRoute
  '/_authenticated/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/_authenticated/microcycles/': typeof AuthenticatedMicrocyclesIndexRoute
  '/_authenticated/preseason/': typeof AuthenticatedPreseasonIndexRoute
  '/_authenticated/season/': typeof AuthenticatedSeasonIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/api/public/security/csp': typeof ApiPublicSecurityCspRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/exercises'
    | '/microcycles'
    | '/preseason'
    | '/season'
    | '/sessions'
    | '/team'
    | '/ejercicios/futbol-base'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/exercises/$id'
    | '/microcycles/$id'
    | '/microcycles/new'
    | '/preseason/$id'
    | '/season/$id'
    | '/sessions/$id'
    | '/sessions/new'
    | '/api/public/health'
    | '/api/rpc/security-probe'
    | '/ejercicios/futbol-base/$slug'
    | '/exercises/'
    | '/microcycles/'
    | '/preseason/'
    | '/season/'
    | '/sessions/'
    | '/api/public/security/csp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/team'
    | '/ejercicios/futbol-base'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/exercises/$id'
    | '/microcycles/$id'
    | '/microcycles/new'
    | '/preseason/$id'
    | '/season/$id'
    | '/sessions/$id'
    | '/sessions/new'
    | '/api/public/health'
    | '/api/rpc/security-probe'
    | '/ejercicios/futbol-base/$slug'
    | '/exercises'
    | '/microcycles'
    | '/preseason'
    | '/season'
    | '/sessions'
    | '/api/public/security/csp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercises'
    | '/_authenticated/microcycles'
    | '/_authenticated/preseason'
    | '/_authenticated/season'
    | '/_authenticated/sessions'
    | '/_authenticated/team'
    | '/ejercicios/futbol-base'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/exercises/$id'
    | '/_authenticated/microcycles/$id'
    | '/_authenticated/microcycles/new'
    | '/_authenticated/preseason/$id'
    | '/_authenticated/season/$id'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/sessions/new'
    | '/api/public/health'
    | '/api/rpc/security-probe'
    | '/ejercicios/futbol-base/$slug'
    | '/_authenticated/exercises/'
    | '/_authenticated/microcycles/'
    | '/_authenticated/preseason/'
    | '/_authenticated/season/'
    | '/_authenticated/sessions/'
    | '/api/public/security/csp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EjerciciosFutbolBaseRoute: typeof EjerciciosFutbolBaseRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiRpcSecurityProbeRoute: typeof ApiRpcSecurityProbeRoute
  ApiPublicSecurityCspRoute: typeof ApiPublicSecurityCspRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/microcycles': {
      id: '/_authenticated/microcycles'
      path: '/microcycles'
      fullPath: '/microcycles'
      preLoaderRoute: typeof AuthenticatedMicrocyclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preseason': {
      id: '/_authenticated/preseason'
      path: '/preseason'
      fullPath: '/preseason'
      preLoaderRoute: typeof AuthenticatedPreseasonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/season': {
      id: '/_authenticated/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof AuthenticatedSeasonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ejercicios/futbol-base': {
      id: '/ejercicios/futbol-base'
      path: '/ejercicios/futbol-base'
      fullPath: '/ejercicios/futbol-base'
      preLoaderRoute: typeof EjerciciosFutbolBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exercises/': {
      id: '/_authenticated/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AuthenticatedExercisesIndexRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
    '/_authenticated/exercises/$id': {
      id: '/_authenticated/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof AuthenticatedExercisesIdRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
    '/_authenticated/microcycles/': {
      id: '/_authenticated/microcycles/'
      path: '/'
      fullPath: '/microcycles/'
      preLoaderRoute: typeof AuthenticatedMicrocyclesIndexRouteImport
      parentRoute: typeof AuthenticatedMicrocyclesRoute
    }
    '/_authenticated/microcycles/$id': {
      id: '/_authenticated/microcycles/$id'
      path: '/$id'
      fullPath: '/microcycles/$id'
      preLoaderRoute: typeof AuthenticatedMicrocyclesIdRouteImport
      parentRoute: typeof AuthenticatedMicrocyclesRoute
    }
    '/_authenticated/microcycles/new': {
      id: '/_authenticated/microcycles/new'
      path: '/new'
      fullPath: '/microcycles/new'
      preLoaderRoute: typeof AuthenticatedMicrocyclesNewRouteImport
      parentRoute: typeof AuthenticatedMicrocyclesRoute
    }
    '/_authenticated/preseason/': {
      id: '/_authenticated/preseason/'
      path: '/'
      fullPath: '/preseason/'
      preLoaderRoute: typeof AuthenticatedPreseasonIndexRouteImport
      parentRoute: typeof AuthenticatedPreseasonRoute
    }
    '/_authenticated/preseason/$id': {
      id: '/_authenticated/preseason/$id'
      path: '/$id'
      fullPath: '/preseason/$id'
      preLoaderRoute: typeof AuthenticatedPreseasonIdRouteImport
      parentRoute: typeof AuthenticatedPreseasonRoute
    }
    '/_authenticated/season/': {
      id: '/_authenticated/season/'
      path: '/'
      fullPath: '/season/'
      preLoaderRoute: typeof AuthenticatedSeasonIndexRouteImport
      parentRoute: typeof AuthenticatedSeasonRoute
    }
    '/_authenticated/season/$id': {
      id: '/_authenticated/season/$id'
      path: '/$id'
      fullPath: '/season/$id'
      preLoaderRoute: typeof AuthenticatedSeasonIdRouteImport
      parentRoute: typeof AuthenticatedSeasonRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/sessions/new': {
      id: '/_authenticated/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedSessionsNewRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/security-probe': {
      id: '/api/rpc/security-probe'
      path: '/api/rpc/security-probe'
      fullPath: '/api/rpc/security-probe'
      preLoaderRoute: typeof ApiRpcSecurityProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejercicios/futbol-base/$slug': {
      id: '/ejercicios/futbol-base/$slug'
      path: '/$slug'
      fullPath: '/ejercicios/futbol-base/$slug'
      preLoaderRoute: typeof EjerciciosFutbolBaseSlugRouteImport
      parentRoute: typeof EjerciciosFutbolBaseRoute
    }
    '/api/public/security/csp': {
      id: '/api/public/security/csp'
      path: '/api/public/security/csp'
      fullPath: '/api/public/security/csp'
      preLoaderRoute: typeof ApiPublicSecurityCspRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedExercisesRouteChildren {
  AuthenticatedExercisesIdRoute: typeof AuthenticatedExercisesIdRoute
  AuthenticatedExercisesIndexRoute: typeof AuthenticatedExercisesIndexRoute
}

const AuthenticatedExercisesRouteChildren: AuthenticatedExercisesRouteChildren =
  {
    AuthenticatedExercisesIdRoute: AuthenticatedExercisesIdRoute,
    AuthenticatedExercisesIndexRoute: AuthenticatedExercisesIndexRoute,
  }

const AuthenticatedExercisesRouteWithChildren =
  AuthenticatedExercisesRoute._addFileChildren(
    AuthenticatedExercisesRouteChildren,
  )

interface AuthenticatedMicrocyclesRouteChildren {
  AuthenticatedMicrocyclesIdRoute: typeof AuthenticatedMicrocyclesIdRoute
  AuthenticatedMicrocyclesNewRoute: typeof AuthenticatedMicrocyclesNewRoute
  AuthenticatedMicrocyclesIndexRoute: typeof AuthenticatedMicrocyclesIndexRoute
}

const AuthenticatedMicrocyclesRouteChildren: AuthenticatedMicrocyclesRouteChildren =
  {
    AuthenticatedMicrocyclesIdRoute: AuthenticatedMicrocyclesIdRoute,
    AuthenticatedMicrocyclesNewRoute: AuthenticatedMicrocyclesNewRoute,
    AuthenticatedMicrocyclesIndexRoute: AuthenticatedMicrocyclesIndexRoute,
  }

const AuthenticatedMicrocyclesRouteWithChildren =
  AuthenticatedMicrocyclesRoute._addFileChildren(
    AuthenticatedMicrocyclesRouteChildren,
  )

interface AuthenticatedPreseasonRouteChildren {
  AuthenticatedPreseasonIdRoute: typeof AuthenticatedPreseasonIdRoute
  AuthenticatedPreseasonIndexRoute: typeof AuthenticatedPreseasonIndexRoute
}

const AuthenticatedPreseasonRouteChildren: AuthenticatedPreseasonRouteChildren =
  {
    AuthenticatedPreseasonIdRoute: AuthenticatedPreseasonIdRoute,
    AuthenticatedPreseasonIndexRoute: AuthenticatedPreseasonIndexRoute,
  }

const AuthenticatedPreseasonRouteWithChildren =
  AuthenticatedPreseasonRoute._addFileChildren(
    AuthenticatedPreseasonRouteChildren,
  )

interface AuthenticatedSeasonRouteChildren {
  AuthenticatedSeasonIdRoute: typeof AuthenticatedSeasonIdRoute
  AuthenticatedSeasonIndexRoute: typeof AuthenticatedSeasonIndexRoute
}

const AuthenticatedSeasonRouteChildren: AuthenticatedSeasonRouteChildren = {
  AuthenticatedSeasonIdRoute: AuthenticatedSeasonIdRoute,
  AuthenticatedSeasonIndexRoute: AuthenticatedSeasonIndexRoute,
}

const AuthenticatedSeasonRouteWithChildren =
  AuthenticatedSeasonRoute._addFileChildren(AuthenticatedSeasonRouteChildren)

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedSessionsNewRoute: typeof AuthenticatedSessionsNewRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedSessionsNewRoute: AuthenticatedSessionsNewRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRouteWithChildren
  AuthenticatedMicrocyclesRoute: typeof AuthenticatedMicrocyclesRouteWithChildren
  AuthenticatedPreseasonRoute: typeof AuthenticatedPreseasonRouteWithChildren
  AuthenticatedSeasonRoute: typeof AuthenticatedSeasonRouteWithChildren
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRouteWithChildren,
  AuthenticatedMicrocyclesRoute: AuthenticatedMicrocyclesRouteWithChildren,
  AuthenticatedPreseasonRoute: AuthenticatedPreseasonRouteWithChildren,
  AuthenticatedSeasonRoute: AuthenticatedSeasonRouteWithChildren,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EjerciciosFutbolBaseRouteChildren {
  EjerciciosFutbolBaseSlugRoute: typeof EjerciciosFutbolBaseSlugRoute
}

const EjerciciosFutbolBaseRouteChildren: EjerciciosFutbolBaseRouteChildren = {
  EjerciciosFutbolBaseSlugRoute: EjerciciosFutbolBaseSlugRoute,
}

const EjerciciosFutbolBaseRouteWithChildren =
  EjerciciosFutbolBaseRoute._addFileChildren(EjerciciosFutbolBaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EjerciciosFutbolBaseRoute: EjerciciosFutbolBaseRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiRpcSecurityProbeRoute: ApiRpcSecurityProbeRoute,
  ApiPublicSecurityCspRoute: ApiPublicSecurityCspRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
