/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMicrocycleSuggestRouteImport } from './routes/api/microcycle-suggest'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedSeasonRouteImport } from './routes/_authenticated/season'
import { Route as AuthenticatedPreseasonRouteImport } from './routes/_authenticated/preseason'
import { Route as AuthenticatedMicrocyclesRouteImport } from './routes/_authenticated/microcycles'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions.index'
import { Route as AuthenticatedSeasonIndexRouteImport } from './routes/_authenticated/season.index'
import { Route as AuthenticatedPreseasonIndexRouteImport } from './routes/_authenticated/preseason.index'
import { Route as AuthenticatedMicrocyclesIndexRouteImport } from './routes/_authenticated/microcycles.index'
import { Route as AuthenticatedExercisesIndexRouteImport } from './routes/_authenticated/exercises.index'
import { Route as AuthenticatedSessionsNewRouteImport } from './routes/_authenticated/sessions.new'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as AuthenticatedSeasonIdRouteImport } from './routes/_authenticated/season.$id'
import { Route as AuthenticatedPreseasonIdRouteImport } from './routes/_authenticated/preseason.$id'
import { Route as AuthenticatedMicrocyclesNewRouteImport } from './routes/_authenticated/microcycles.new'
import { Route as AuthenticatedMicrocyclesIdRouteImport } from './routes/_authenticated/microcycles.$id'
import { Route as AuthenticatedExercisesIdRouteImport } from './routes/_authenticated/exercises.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMicrocycleSuggestRoute = ApiMicrocycleSuggestRouteImport.update({
  id: '/api/microcycle-suggest',
  path: '/api/microcycle-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeasonRoute = AuthenticatedSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreseasonRoute = AuthenticatedPreseasonRouteImport.update({
  id: '/preseason',
  path: '/preseason',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMicrocyclesRoute =
  AuthenticatedMicrocyclesRouteImport.update({
    id: '/microcycles',
    path: '/microcycles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedSeasonIndexRoute =
  AuthenticatedSeasonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSeasonRoute,
  } as any)
const AuthenticatedPreseasonIndexRoute =
  AuthenticatedPreseasonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPreseasonRoute,
  } as any)
const AuthenticatedMicrocyclesIndexRoute =
  AuthenticatedMicrocyclesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMicrocyclesRoute,
  } as any)
const AuthenticatedExercisesIndexRoute =
  AuthenticatedExercisesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)
const AuthenticatedSessionsNewRoute =
  AuthenticatedSessionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSessionsRoute,
} as any)
const AuthenticatedSeasonIdRoute = AuthenticatedSeasonIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSeasonRoute,
} as any)
const AuthenticatedPreseasonIdRoute =
  AuthenticatedPreseasonIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPreseasonRoute,
  } as any)
const AuthenticatedMicrocyclesNewRoute =
  AuthenticatedMicrocyclesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMicrocyclesRoute,
  } as any)
const AuthenticatedMicrocyclesIdRoute =
  AuthenticatedMicrocyclesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMicrocyclesRoute,
  } as any)
const AuthenticatedExercisesIdRoute =
  AuthenticatedExercisesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/microcycles': typeof AuthenticatedMicrocyclesRouteWithChildren
  '/preseason': typeof AuthenticatedPreseasonRouteWithChildren
  '/season': typeof AuthenticatedSeasonRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/api/microcycle-suggest': typeof ApiMicrocycleSuggestRoute
  '/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/microcycles/$id': typeof AuthenticatedMicrocyclesIdRoute
  '/microcycles/new': typeof AuthenticatedMicrocyclesNewRoute
  '/preseason/$id': typeof AuthenticatedPreseasonIdRoute
  '/season/$id': typeof AuthenticatedSeasonIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/microcycles/': typeof AuthenticatedMicrocyclesIndexRoute
  '/preseason/': typeof AuthenticatedPreseasonIndexRoute
  '/season/': typeof AuthenticatedSeasonIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/team': typeof AuthenticatedTeamRoute
  '/api/microcycle-suggest': typeof ApiMicrocycleSuggestRoute
  '/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/microcycles/$id': typeof AuthenticatedMicrocyclesIdRoute
  '/microcycles/new': typeof AuthenticatedMicrocyclesNewRoute
  '/preseason/$id': typeof AuthenticatedPreseasonIdRoute
  '/season/$id': typeof AuthenticatedSeasonIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/exercises': typeof AuthenticatedExercisesIndexRoute
  '/microcycles': typeof AuthenticatedMicrocyclesIndexRoute
  '/preseason': typeof AuthenticatedPreseasonIndexRoute
  '/season': typeof AuthenticatedSeasonIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/_authenticated/microcycles': typeof AuthenticatedMicrocyclesRouteWithChildren
  '/_authenticated/preseason': typeof AuthenticatedPreseasonRouteWithChildren
  '/_authenticated/season': typeof AuthenticatedSeasonRouteWithChildren
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/api/microcycle-suggest': typeof ApiMicrocycleSuggestRoute
  '/_authenticated/exercises/$id': typeof AuthenticatedExercisesIdRoute
  '/_authenticated/microcycles/$id': typeof AuthenticatedMicrocyclesIdRoute
  '/_authenticated/microcycles/new': typeof AuthenticatedMicrocyclesNewRoute
  '/_authenticated/preseason/$id': typeof AuthenticatedPreseasonIdRoute
  '/_authenticated/season/$id': typeof AuthenticatedSeasonIdRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/_authenticated/exercises/': typeof AuthenticatedExercisesIndexRoute
  '/_authenticated/microcycles/': typeof AuthenticatedMicrocyclesIndexRoute
  '/_authenticated/preseason/': typeof AuthenticatedPreseasonIndexRoute
  '/_authenticated/season/': typeof AuthenticatedSeasonIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/exercises'
    | '/microcycles'
    | '/preseason'
    | '/season'
    | '/sessions'
    | '/team'
    | '/api/microcycle-suggest'
    | '/exercises/$id'
    | '/microcycles/$id'
    | '/microcycles/new'
    | '/preseason/$id'
    | '/season/$id'
    | '/sessions/$id'
    | '/sessions/new'
    | '/exercises/'
    | '/microcycles/'
    | '/preseason/'
    | '/season/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/team'
    | '/api/microcycle-suggest'
    | '/exercises/$id'
    | '/microcycles/$id'
    | '/microcycles/new'
    | '/preseason/$id'
    | '/season/$id'
    | '/sessions/$id'
    | '/sessions/new'
    | '/exercises'
    | '/microcycles'
    | '/preseason'
    | '/season'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercises'
    | '/_authenticated/microcycles'
    | '/_authenticated/preseason'
    | '/_authenticated/season'
    | '/_authenticated/sessions'
    | '/_authenticated/team'
    | '/api/microcycle-suggest'
    | '/_authenticated/exercises/$id'
    | '/_authenticated/microcycles/$id'
    | '/_authenticated/microcycles/new'
    | '/_authenticated/preseason/$id'
    | '/_authenticated/season/$id'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/sessions/new'
    | '/_authenticated/exercises/'
    | '/_authenticated/microcycles/'
    | '/_authenticated/preseason/'
    | '/_authenticated/season/'
    | '/_authenticated/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiMicrocycleSuggestRoute: typeof ApiMicrocycleSuggestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/microcycle-suggest': {
      id: '/api/microcycle-suggest'
      path: '/api/microcycle-suggest'
      fullPath: '/api/microcycle-suggest'
      preLoaderRoute: typeof ApiMicrocycleSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/season': {
      id: '/_authenticated/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof AuthenticatedSeasonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preseason': {
      id: '/_authenticated/preseason'
      path: '/preseason'
      fullPath: '/preseason'
      preLoaderRoute: typeof AuthenticatedPreseasonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/microcycles': {
      id: '/_authenticated/microcycles'
      path: '/microcycles'
      fullPath: '/microcycles'
      preLoaderRoute: typeof AuthenticatedMicrocyclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/season/': {
      id: '/_authenticated/season/'
      path: '/'
      fullPath: '/season/'
      preLoaderRoute: typeof AuthenticatedSeasonIndexRouteImport
      parentRoute: typeof AuthenticatedSeasonRoute
    }
    '/_authenticated/preseason/': {
      id: '/_authenticated/preseason/'
      path: '/'
      fullPath: '/preseason/'
      preLoaderRoute: typeof AuthenticatedPreseasonIndexRouteImport
      parentRoute: typeof AuthenticatedPreseasonRoute
    }
    '/_authenticated/microcycles/': {
      id: '/_authenticated/microcycles/'
      path: '/'
      fullPath: '/microcycles/'
      preLoaderRoute: typeof AuthenticatedMicrocyclesIndexRouteImport
      parentRoute: typeof AuthenticatedMicrocyclesRoute
    }
    '/_authenticated/exercises/': {
      id: '/_authenticated/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof AuthenticatedExercisesIndexRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
    '/_authenticated/sessions/new': {
      id: '/_authenticated/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedSessionsNewRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/season/$id': {
      id: '/_authenticated/season/$id'
      path: '/$id'
      fullPath: '/season/$id'
      preLoaderRoute: typeof AuthenticatedSeasonIdRouteImport
      parentRoute: typeof AuthenticatedSeasonRoute
    }
    '/_authenticated/preseason/$id': {
      id: '/_authenticated/preseason/$id'
      path: '/$id'
      fullPath: '/preseason/$id'
      preLoaderRoute: typeof AuthenticatedPreseasonIdRouteImport
      parentRoute: typeof AuthenticatedPreseasonRoute
    }
    '/_authenticated/microcycles/new': {
      id: '/_authenticated/microcycles/new'
      path: '/new'
      fullPath: '/microcycles/new'
      preLoaderRoute: typeof AuthenticatedMicrocyclesNewRouteImport
      parentRoute: typeof AuthenticatedMicrocyclesRoute
    }
    '/_authenticated/microcycles/$id': {
      id: '/_authenticated/microcycles/$id'
      path: '/$id'
      fullPath: '/microcycles/$id'
      preLoaderRoute: typeof AuthenticatedMicrocyclesIdRouteImport
      parentRoute: typeof AuthenticatedMicrocyclesRoute
    }
    '/_authenticated/exercises/$id': {
      id: '/_authenticated/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof AuthenticatedExercisesIdRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
  }
}

interface AuthenticatedExercisesRouteChildren {
  AuthenticatedExercisesIdRoute: typeof AuthenticatedExercisesIdRoute
  AuthenticatedExercisesIndexRoute: typeof AuthenticatedExercisesIndexRoute
}

const AuthenticatedExercisesRouteChildren: AuthenticatedExercisesRouteChildren =
  {
    AuthenticatedExercisesIdRoute: AuthenticatedExercisesIdRoute,
    AuthenticatedExercisesIndexRoute: AuthenticatedExercisesIndexRoute,
  }

const AuthenticatedExercisesRouteWithChildren =
  AuthenticatedExercisesRoute._addFileChildren(
    AuthenticatedExercisesRouteChildren,
  )

interface AuthenticatedMicrocyclesRouteChildren {
  AuthenticatedMicrocyclesIdRoute: typeof AuthenticatedMicrocyclesIdRoute
  AuthenticatedMicrocyclesNewRoute: typeof AuthenticatedMicrocyclesNewRoute
  AuthenticatedMicrocyclesIndexRoute: typeof AuthenticatedMicrocyclesIndexRoute
}

const AuthenticatedMicrocyclesRouteChildren: AuthenticatedMicrocyclesRouteChildren =
  {
    AuthenticatedMicrocyclesIdRoute: AuthenticatedMicrocyclesIdRoute,
    AuthenticatedMicrocyclesNewRoute: AuthenticatedMicrocyclesNewRoute,
    AuthenticatedMicrocyclesIndexRoute: AuthenticatedMicrocyclesIndexRoute,
  }

const AuthenticatedMicrocyclesRouteWithChildren =
  AuthenticatedMicrocyclesRoute._addFileChildren(
    AuthenticatedMicrocyclesRouteChildren,
  )

interface AuthenticatedPreseasonRouteChildren {
  AuthenticatedPreseasonIdRoute: typeof AuthenticatedPreseasonIdRoute
  AuthenticatedPreseasonIndexRoute: typeof AuthenticatedPreseasonIndexRoute
}

const AuthenticatedPreseasonRouteChildren: AuthenticatedPreseasonRouteChildren =
  {
    AuthenticatedPreseasonIdRoute: AuthenticatedPreseasonIdRoute,
    AuthenticatedPreseasonIndexRoute: AuthenticatedPreseasonIndexRoute,
  }

const AuthenticatedPreseasonRouteWithChildren =
  AuthenticatedPreseasonRoute._addFileChildren(
    AuthenticatedPreseasonRouteChildren,
  )

interface AuthenticatedSeasonRouteChildren {
  AuthenticatedSeasonIdRoute: typeof AuthenticatedSeasonIdRoute
  AuthenticatedSeasonIndexRoute: typeof AuthenticatedSeasonIndexRoute
}

const AuthenticatedSeasonRouteChildren: AuthenticatedSeasonRouteChildren = {
  AuthenticatedSeasonIdRoute: AuthenticatedSeasonIdRoute,
  AuthenticatedSeasonIndexRoute: AuthenticatedSeasonIndexRoute,
}

const AuthenticatedSeasonRouteWithChildren =
  AuthenticatedSeasonRoute._addFileChildren(AuthenticatedSeasonRouteChildren)

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedSessionsNewRoute: typeof AuthenticatedSessionsNewRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedSessionsNewRoute: AuthenticatedSessionsNewRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRouteWithChildren
  AuthenticatedMicrocyclesRoute: typeof AuthenticatedMicrocyclesRouteWithChildren
  AuthenticatedPreseasonRoute: typeof AuthenticatedPreseasonRouteWithChildren
  AuthenticatedSeasonRoute: typeof AuthenticatedSeasonRouteWithChildren
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRouteWithChildren,
  AuthenticatedMicrocyclesRoute: AuthenticatedMicrocyclesRouteWithChildren,
  AuthenticatedPreseasonRoute: AuthenticatedPreseasonRouteWithChildren,
  AuthenticatedSeasonRoute: AuthenticatedSeasonRouteWithChildren,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiMicrocycleSuggestRoute: ApiMicrocycleSuggestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
