// This file is automatically generated and enhanced for offline/portable resilience.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type RuntimeConfig = { supabaseUrl?: string; supabasePublishableKey?: string };

function getRuntimeConfig(): RuntimeConfig {
  if (typeof globalThis !== 'undefined' && '__PLANEOfut_CONFIG__' in globalThis) {
    return (globalThis as typeof globalThis & { __PLANEOfut_CONFIG__?: RuntimeConfig }).__PLANEOfut_CONFIG__ ?? {};
  }
  return {};
}

function createQueryBuilderStub() {
  const chainable: any = {
    select: () => chainable,
    insert: () => chainable,
    update: () => chainable,
    delete: () => chainable,
    eq: () => chainable,
    neq: () => chainable,
    gt: () => chainable,
    gte: () => chainable,
    lt: () => chainable,
    lte: () => chainable,
    like: () => chainable,
    ilike: () => chainable,
    is: () => chainable,
    in: () => chainable,
    contains: () => chainable,
    containedBy: () => chainable,
    range: () => chainable,
    order: () => chainable,
    limit: () => chainable,
    single: async () => ({ data: null, error: null }),
    maybeSingle: async () => ({ data: null, error: null }),
    then: (onfulfilled?: any) => Promise.resolve({ data: [], error: null, count: 0 }).then(onfulfilled),
    catch: (onrejected?: any) => Promise.resolve({ data: [], error: null, count: 0 }).catch(onrejected),
  };
  return chainable;
}

function createStubClient() {
  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => undefined } },
      }),
      signOut: async () => ({ error: null }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: { message: "Supabase no configurado en portable-config.json" } }),
      signUp: async () => ({ data: { user: null, session: null }, error: { message: "Supabase no configurado en portable-config.json" } }),
      resetPasswordForEmail: async () => ({ data: {}, error: { message: "Supabase no configurado en portable-config.json" } }),
      updateUser: async () => ({ data: { user: null }, error: { message: "Supabase no configurado en portable-config.json" } }),
    },
    from: () => createQueryBuilderStub(),
    rpc: async () => ({ data: null, error: null }),
    channel: () => ({
      on: () => ({ subscribe: () => ({ unsubscribe: () => undefined }) }),
      subscribe: () => ({ unsubscribe: () => undefined }),
    }),
    removeChannel: () => undefined,
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  const runtimeConfig = getRuntimeConfig();
  const SUPABASE_URL = runtimeConfig.supabaseUrl || import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = runtimeConfig.supabasePublishableKey || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      '[Supabase] Credenciales no configuradas. PlaneoFUT ejecutará en modo local/offline resiliente.'
    );
    return createStubClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as NonNullable<ReturnType<typeof createSupabaseClient>>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    const target = _supabase || createStubClient();
    const value = Reflect.get(target, prop, receiver);
    if (value === undefined && prop === 'from') {
      return () => createQueryBuilderStub();
    }
    return value;
  },
});
